-- MySQL Script generated by MySQL Workbench
-- Fri Apr  2 21:24:00 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema image_board
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema image_board
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `image_board` DEFAULT CHARACTER SET utf8 ;
USE `image_board` ;

-- -----------------------------------------------------
-- Table `image_board`.`boards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `image_board`.`boards` ;

CREATE TABLE IF NOT EXISTS `image_board`.`boards` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uri` VARCHAR(5) NOT NULL,
  `name` TINYTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `image_board`.`threads`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `image_board`.`threads` ;

CREATE TABLE IF NOT EXISTS `image_board`.`threads` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `board` INT NOT NULL,
  `sticky` TINYINT NOT NULL DEFAULT 0,
  `date_bumped` DATETIME NOT NULL DEFAULT now(),
  `title` VARCHAR(100) NULL DEFAULT '',
  PRIMARY KEY (`id`),
  INDEX `board_idx` (`board` ASC) VISIBLE,
  CONSTRAINT `thread_board`
    FOREIGN KEY (`board`)
    REFERENCES `image_board`.`boards` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `thread_op`
    FOREIGN KEY (`id`)
    REFERENCES `image_board`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `image_board`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `image_board`.`posts` ;

CREATE TABLE IF NOT EXISTS `image_board`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comment` TEXT NOT NULL,
  `author` VARCHAR(45) NOT NULL DEFAULT 'Anonymous',
  `date_posted` DATETIME NOT NULL DEFAULT now(),
  `image` INT NULL,
  `thread` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `thread_idx` (`thread` ASC) VISIBLE,
  CONSTRAINT `post_thread`
    FOREIGN KEY (`thread`)
    REFERENCES `image_board`.`threads` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `image_board` ;

-- -----------------------------------------------------
-- procedure new_thread
-- -----------------------------------------------------

USE `image_board`;
DROP procedure IF EXISTS `image_board`.`new_thread`;

DELIMITER $$
USE `image_board`$$
CREATE PROCEDURE `new_thread` (board_id INT, new_title VARCHAR(100), new_comment TEXT, new_author VARCHAR(45))
BEGIN
	START TRANSACTION;
    INSERT INTO `posts` (comment, author) VALUES (new_comment, new_author);
    SET @post_id = LAST_INSERT_ID();
    INSERT INTO `threads` (id, board, title) VALUES (@post_id, board_id, new_title);
    UPDATE `posts` SET thread = LAST_INSERT_ID() WHERE id = @post_id;
    COMMIT;
END;$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure new_reply
-- -----------------------------------------------------

USE `image_board`;
DROP procedure IF EXISTS `image_board`.`new_reply`;

DELIMITER $$
USE `image_board`$$
CREATE PROCEDURE `new_reply` (new_comment TEXT, new_author VARCHAR(45), thread_id INT)
BEGIN
	START TRANSACTION;
    INSERT INTO `posts` (comment, author, thread) VALUES (new_comment, new_author, thread_id);
    UPDATE `threads` SET date_bumped = (SELECT date_posted FROM `posts` WHERE id = LAST_INSERT_ID()) WHERE id = thread_id;
    COMMIT;
END;$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure get_board_threads
-- -----------------------------------------------------

USE `image_board`;
DROP procedure IF EXISTS `image_board`.`get_board_threads`;

DELIMITER $$
USE `image_board`$$
CREATE PROCEDURE `get_board_threads` (board_id INT)
BEGIN
	SELECT * FROM threads WHERE board = board_id ORDER BY date_bumped DESC;
END;$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure get_thread_op
-- -----------------------------------------------------

USE `image_board`;
DROP procedure IF EXISTS `image_board`.`get_thread_op`;

DELIMITER $$
USE `image_board`$$
CREATE PROCEDURE `get_thread_op` (thread_id INT)
BEGIN
	SELECT * FROM posts WHERE thread = thread_id ORDER BY date_posted ASC LIMIT 1;
END;$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure get_thread_replies
-- -----------------------------------------------------

USE `image_board`;
DROP procedure IF EXISTS `image_board`.`get_thread_replies`;

DELIMITER $$
USE `image_board`$$
CREATE PROCEDURE `get_thread_replies` (thread_id INT)
BEGIN
	SELECT * FROM posts WHERE thread = thread_id ORDER BY date_posted ASC LIMIT 1, 500;
END;$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure delete_thread
-- -----------------------------------------------------

USE `image_board`;
DROP procedure IF EXISTS `image_board`.`delete_thread`;

DELIMITER $$
USE `image_board`$$
CREATE PROCEDURE `delete_thread` (thread_id int)
BEGIN
	START TRANSACTION;
    DELETE FROM `threads` WHERE id = thread_id;
    COMMIT;
END;$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure delete_post
-- -----------------------------------------------------

USE `image_board`;
DROP procedure IF EXISTS `image_board`.`delete_post`;

DELIMITER $$
USE `image_board`$$
CREATE PROCEDURE `delete_post` (post_id int)
BEGIN
	START TRANSACTION;
    DELETE FROM `posts` WHERE id = post_id;
    COMMIT;
END;$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
